const actionTypes = {
	ADD_ALBUM: 'ADD_ALBUM',
	ADD_SONG: 'ADD_SONG',
	REMOVE_ALBUM: 'REMOVE_ALBUM',
	REMOVE_SONG: 'REMOVE_SONG',
	SET_ERROR: 'SET_ERROR',
	TOGGLE_IS_ADDING_SONG: 'TOGGLE_IS_ADDING_SONG',
	TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',
	UPDATE_ALBUM: 'UPDATE_ALBUM',
	UPDATE_SONG: 'UPDATE_SONG',
};

export default actionTypes;
