const actionTypes = {
	// Audio Player Actions
	SET_SONG: 'SET_SONG',
	SET_PLAYER_STATUS: 'SET_PLAYER_STATUS',

	TOGGLE_PLAYER_LOADING: 'TOGGLE_PLAYER_LOADING',
	TOGGLE_PLAYER_VISIBLE: 'TOGGLE_PLAYER_VISIBLE',
	TOGGLE_PLAYER_IS_MUTED: 'TOGGLE_PLAYER_IS_MUTED',

	// CMS Actions
	ADD_ALBUM: 'ADD_ALBUM',
	ADD_SONG: 'ADD_SONG',
	REMOVE_ALBUM: 'REMOVE_ALBUM',
	REMOVE_SONG: 'REMOVE_SONG',
	SET_ALBUMS: 'SET_ALBUMS',
	SET_ERROR: 'SET_ERROR',
	SET_SONGS: 'SET_SONGS',
	TOGGLE_IS_ADDING_SONG: 'TOGGLE_IS_ADDING_SONG',
	SET_UPDATE_SONG_DETAILS: 'SET_UPDATE_SONG_DETAILS',
	TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',
	UPDATE_ALBUM: 'UPDATE_ALBUM',
	UPDATE_SONG: 'UPDATE_SONG',
	SET_REPLACE_AUDIO: 'SET_REPLACE_AUDIO',
	SET_UPDATING_ALBUM: 'SET_UPDATING_ALBUM',
};

export default actionTypes;
